// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must not run over Supabase's transaction-mode pooler (port 6543):
    // `migrate deploy` takes a session-level advisory lock, which pgbouncer in
    // transaction mode never grants, so the command hangs until the build times out.
    // DIRECT_URL is the session-mode pooler (port 5432). Runtime keeps DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
